// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEsWLXbMdldqF7cHXC1xF5D7T9GYxh48s',
    appId: '1:485218920004:web:f6dbb6c537ca5eaf2cbe11',
    messagingSenderId: '485218920004',
    projectId: 'gym-log-a73ef',
    authDomain: 'gym-log-a73ef.firebaseapp.com',
    storageBucket: 'gym-log-a73ef.firebasestorage.app',
    measurementId: 'G-TP1JNZX12S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQMY6miH_g7FyG7je-vE9RVA48XQHzCrk',
    appId: '1:485218920004:android:dfde74cac31a8c3f2cbe11',
    messagingSenderId: '485218920004',
    projectId: 'gym-log-a73ef',
    storageBucket: 'gym-log-a73ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVzLkA5NQemXc45uUXN_lYdA7Scyd8X18',
    appId: '1:485218920004:ios:7de3cba1d35e44472cbe11',
    messagingSenderId: '485218920004',
    projectId: 'gym-log-a73ef',
    storageBucket: 'gym-log-a73ef.firebasestorage.app',
    iosBundleId: 'com.example.gymLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVzLkA5NQemXc45uUXN_lYdA7Scyd8X18',
    appId: '1:485218920004:ios:7de3cba1d35e44472cbe11',
    messagingSenderId: '485218920004',
    projectId: 'gym-log-a73ef',
    storageBucket: 'gym-log-a73ef.firebasestorage.app',
    iosBundleId: 'com.example.gymLog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEsWLXbMdldqF7cHXC1xF5D7T9GYxh48s',
    appId: '1:485218920004:web:78c577600a346d472cbe11',
    messagingSenderId: '485218920004',
    projectId: 'gym-log-a73ef',
    authDomain: 'gym-log-a73ef.firebaseapp.com',
    storageBucket: 'gym-log-a73ef.firebasestorage.app',
    measurementId: 'G-XZ3BSLPFGK',
  );
}
